name: 'Cletus Code Review'
description: 'AI-powered pull request review with plugin support and auto-merge capabilities'
branding:
  icon: 'eye'
  color: 'purple'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}

  changed-files:
    description: 'JSON array of changed file paths from changed-files action'
    required: true

  skill:
    description: 'Specific review skill to use (default: auto-detect from repo)'
    required: false

  output-dir:
    description: 'Directory for output files'
    required: false
    default: 'output'

  claude-args:
    description: 'Additional arguments to pass to Claude Code action'
    required: false
    default: '--dangerously-skip-permissions'

  anthropic-api-key:
    description: 'Anthropic API key for Claude Code'
    required: true

  schema-file:
    description: 'Path to schema file for review validation'
    required: false

  settings:
    description: 'JSON settings for Claude Code (for MCP servers, etc)'
    required: false

runs:
  using: 'composite'
  steps:
    # Setup Python
    - name: Setup Python
      shell: bash
      run: |
        if command -v uv &> /dev/null; then
          echo "uv already installed"
        else
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        fi
        uv --version
        uv python install 3.13

    # Run the review orchestrator
    - name: Run review orchestrator
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        CHANGED_FILES: ${{ inputs.changed-files }}
        CLETUS_SKILL: ${{ inputs.skill }}
        OUTPUT_DIR: ${{ inputs.output-dir }}
        REVIEW_SCHEMA_FILE: ${{ inputs.schema-file }}
      run: |
        cd ${{ github.action_path }}/..
        uv run --python 3.13 -m cletus_code.run_review \
          --changed-files "${{ inputs.changed-files }}" \
          ${{ inputs.skill != '' && format('--skill {0}', inputs.skill) || '' }} \
          --output-dir "${{ inputs.output-dir }}"

    # Run Claude Code with the generated prompt
    - name: Run Claude Code
      uses: anthropics/claude-code-action@v1
      with:
        prompt: ${{ github.action_path }}/../${{ inputs.output-dir }}/claude-prompt.md
        anthropic_api_key: ${{ inputs.anthropic-api-key }}
        github_token: ${{ inputs.github-token }}
        claude_args: ${{ inputs.claude-args }}
        settings: ${{ inputs.settings }}

    # Process and publish the review results
    - name: Process review results
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        OUTPUT_DIR: ${{ inputs.output-dir }}
        REVIEW_SCHEMA_FILE: ${{ inputs.schema-file }}
      run: |
        cd ${{ github.action_path }}/..
        uv run --python 3.13 -m cletus_code.process_review \
          --output-dir "${{ inputs.output-dir }}" \
          ${{ inputs.schema-file != '' && format('--schema-file {0}', inputs.schema-file) || '' }}
