name: 'Cletus Code Review'
description: 'AI-powered pull request review with plugin support, structured output, and auto-merge capabilities'
branding:
  icon: 'eye'
  color: 'purple'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}

  changed-files:
    description: 'JSON array of changed file paths from changed-files action'
    required: true

  skills:
    description: 'Array of review skills to use. Formats: local:skill-name, owner/repo:ref:skill-path, url:https://..., builtin:name'
    required: false

  extra-skills:
    description: 'Additional skills to include alongside defaults (JSON array string)'
    required: false

  output-dir:
    description: 'Directory for output files'
    required: false
    default: 'output'

  claude-args:
    description: 'Additional arguments to pass to Claude Code action'
    required: false
    default: '--dangerously-skip-permissions'

  anthropic-api-key:
    description: 'Anthropic API key for Claude Code'
    required: true

  schema-file:
    description: 'Path to schema file for review validation'
    required: false

  settings:
    description: 'JSON settings for Claude Code (for MCP servers, etc)'
    required: false

runs:
  using: 'composite'
  steps:
    # Setup Python
    - name: Setup Python
      shell: bash
      run: |
        if command -v uv &> /dev/null; then
          echo "uv already installed"
        else
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
        fi
        export PATH="$HOME/.local/bin:$PATH"
        uv --version
        uv python install 3.13

    # Run the review orchestrator
    - name: Run review orchestrator
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        CHANGED_FILES: ${{ inputs.changed-files }}
        CLETUS_SKILLS: ${{ inputs.skills }}
        CLETUS_EXTRA_SKILLS: ${{ inputs.extra-skills }}
        OUTPUT_DIR: ${{ inputs.output-dir }}
        REVIEW_SCHEMA_FILE: ${{ inputs.schema-file }}
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        cd ${{ github.action_path }}
        uv run --python 3.13 -m cletus_code.run_review \
          --changed-files '${{ inputs.changed-files }}' \
          ${{ inputs.skills != '' && format('--skills-json ''{0}''', inputs.skills) || '' }} \
          ${{ inputs.extra-skills != '' && format('--extra-skills ''{0}''', inputs.extra-skills) || '' }} \
          --output-dir "${{ inputs.output-dir }}"

    # Read the JSON schema content to pass inline to --json-schema flag
    # The claude-code-action requires the schema as an inline JSON string, not a file path
    - name: Load JSON Schema
      id: load-schema
      shell: bash
      run: |
        SCHEMA_FILE="${{ github.action_path }}/${{ inputs.output-dir }}/review-schema.json"
        if [ -f "$SCHEMA_FILE" ]; then
          # Read the schema and escape it for use in GitHub Actions
          # Remove newlines and escape quotes
          SCHEMA_CONTENT=$(cat "$SCHEMA_FILE" | jq -c .)
          # Add to GITHUB_OUTPUT so it can be used in subsequent steps
          {
            echo "schema=${SCHEMA_CONTENT}"
          } >> "$GITHUB_OUTPUT"
          echo "Schema loaded successfully"
        else
          echo "Error: Schema file not found at $SCHEMA_FILE"
          exit 1
        fi

    # Run Claude Code with the generated prompt and JSON schema for structured output
    - name: Run Claude Code
      id: claude-review
      uses: anthropics/claude-code-action/base-action@7145c3e0510bcdbdd29f67cc4a8c1958f1acfa2f # v1.0.27
      with:
        prompt_file: ${{ github.action_path }}/${{ inputs.output-dir }}/claude-prompt.md
        anthropic_api_key: ${{ inputs.anthropic-api-key }}
        # Use structured output with JSON schema to guarantee review.json creation
        # Note: --json-schema expects an inline JSON string, not a file path
        claude_args: |
          ${{ inputs.claude-args }} --json-schema '${{ steps.load-schema.outputs.schema }}'
        settings: ${{ inputs.settings }}
        show_full_output: 'true'
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        ANTHROPIC_API_KEY: ${{ inputs.anthropic-api-key }}

    # Extract structured output and write to review.json
    - name: Write review.json from structured output
      shell: pwsh
      run: |
        # PowerShell handles special characters in JSON better than bash
        $outputDir = "${{ github.action_path }}/${{ inputs.output-dir }}"
        New-Item -ItemType Directory -Force -Path $outputDir | Out-Null

        $structuredOutput = "${{ steps.claude-review.outputs.structured_output }}"

        if (-not [string]::IsNullOrWhiteSpace($structuredOutput)) {
          $structuredOutput | Out-File -FilePath "$outputDir/review.json" -Encoding utf8
          Write-Host "Successfully wrote review.json"
        } else {
          Write-Host "Warning: structured_output is empty, checking workspace..."
          # Fallback to checking workspace (old behavior)
          $workspaceReview = "${{ github.workspace }}/output/review.json"
          if (Test-Path $workspaceReview) {
            Copy-Item $workspaceReview "$outputDir/review.json"
            Write-Host "Copied review.json from workspace to action directory"
          } else {
            Write-Host "Error: review.json not found from structured_output or workspace"
            Get-ChildItem "${{ github.workspace }}/output/" -ErrorAction SilentlyContinue | Out-Host
            exit 1
          }
        }

    # Process and publish the review results
    - name: Process review results
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        OUTPUT_DIR: ${{ inputs.output-dir }}
        REVIEW_SCHEMA_FILE: ${{ inputs.schema-file }}
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        cd ${{ github.action_path }}
        uv run --python 3.13 -m cletus_code.process_review \
          --output-dir "${{ inputs.output-dir }}" \
          ${{ inputs.schema-file != '' && format('--schema-file {0}', inputs.schema-file) || '' }}
