name: 'Cletus Code Review'
description: 'AI-powered pull request review with plugin support, structured output, and auto-merge capabilities'
branding:
  icon: 'eye'
  color: 'purple'

inputs:
  github-token:
    description: 'GitHub token for API access (defaults to github.token, but GITHUB_APP_TOKEN is recommended for custom app identity)'
    required: true
    default: ${{ github.token }}

  github-app-token:
    description: 'GitHub App token for using custom app identity (e.g., "Cletus Code" app). If provided, this takes precedence over github-token.'
    required: false

  changed-files:
    description: 'JSON array of changed file paths from changed-files action'
    required: true

  skills:
    description: 'Array of review skills to use. Formats: local:skill-name, owner/repo:ref:skill-path, url:https://..., builtin:name'
    required: false

  extra-skills:
    description: 'Additional skills to include alongside defaults (JSON array string)'
    required: false

  output-dir:
    description: 'Directory for output files'
    required: false
    default: 'output'

  claude-args:
    description: 'Additional arguments to pass to Claude Code action'
    required: false
    default: '--dangerously-skip-permissions'

  anthropic-api-key:
    description: 'Anthropic API key for Claude Code'
    required: true

  schema-file:
    description: 'Path to schema file for review validation'
    required: false

  settings:
    description: 'JSON settings for Claude Code (for MCP servers, etc)'
    required: false

runs:
  using: 'composite'
  steps:
    # Setup Python
    - name: Setup Python
      shell: bash
      run: |
        if command -v uv &> /dev/null; then
          echo "uv already installed"
        else
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
        fi
        export PATH="$HOME/.local/bin:$PATH"
        uv --version
        uv python install 3.13

    # Run the review orchestrator
    - name: Run review orchestrator
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-app-token || inputs.github-token }}
        CHANGED_FILES: ${{ inputs.changed-files }}
        CLETUS_SKILLS: ${{ inputs.skills }}
        CLETUS_EXTRA_SKILLS: ${{ inputs.extra-skills }}
        OUTPUT_DIR: ${{ inputs.output-dir }}
        REVIEW_SCHEMA_FILE: ${{ inputs.schema-file }}
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        cd ${{ github.action_path }}
        uv run --python 3.13 -m cletus_code.run_review \
          --changed-files '${{ inputs.changed-files }}' \
          ${{ inputs.skills != '' && format('--skills-json ''{0}''', inputs.skills) || '' }} \
          ${{ inputs.extra-skills != '' && format('--extra-skills ''{0}''', inputs.extra-skills) || '' }} \
          --output-dir "${{ inputs.output-dir }}"

    # Run Claude Code with the generated prompt
    # The prompt itself will instruct Claude to output JSON
    - name: Run Claude Code
      id: claude-review
      uses: anthropics/claude-code-action/base-action@7145c3e0510bcdbdd29f67cc4a8c1958f1acfa2f # v1.0.27
      with:
        prompt_file: ${{ github.action_path }}/${{ inputs.output-dir }}/claude-prompt.md
        anthropic_api_key: ${{ inputs.anthropic-api-key }}
        claude_args: ${{ inputs.claude-args }}
        settings: ${{ inputs.settings }}
        show_full_output: 'true'
      env:
        GITHUB_TOKEN: ${{ inputs.github-app-token || inputs.github-token }}
        ANTHROPIC_API_KEY: ${{ inputs.anthropic-api-key }}

    # Extract JSON from Claude's output and write to review.json
    - name: Write review.json from Claude output
      shell: bash
      run: |
        set -e

        OUTPUT_DIR="${{ github.action_path }}/${{ inputs.output-dir }}"
        EXECUTION_FILE="${{ steps.claude-review.outputs.execution_file }}"

        if [ -f "$EXECUTION_FILE" ]; then
          # Extract JSON from the execution file using a Python script
          cat > /tmp/extract_json.py << 'PYEOF'
import json
import re
import sys

execution_file = sys.argv[1]
output_file = sys.argv[2]

with open(execution_file, 'r') as f:
    content = f.read()

# Try to find a JSON object in the content
# Look for content between ```json and ``` markers
json_match = re.search(r'```json\s*(.*?)\s*```', content, re.DOTALL)
if json_match:
    json_str = json_match.group(1)
else:
    # Try to find a raw JSON object
    json_match = re.search(r'\{[^{}]*(?:\{[^{}]*\}[^{}]*)*\}', content, re.DOTALL)
    if json_match:
        json_str = json_match.group(0)
    else:
        print("Error: Could not find JSON in Claude output")
        sys.exit(1)

try:
    data = json.loads(json_str)
    with open(output_file, 'w') as f:
        json.dump(data, f, indent=2)
    print(f"Successfully wrote review.json")
except json.JSONDecodeError as e:
    print(f"Error: Invalid JSON: {e}")
    print(f"JSON string was: {json_str[:500]}...")
    sys.exit(1)
PYEOF

          python3 /tmp/extract_json.py "$EXECUTION_FILE" "$OUTPUT_DIR/review.json"
        else
          echo "Error: Execution file not found at $EXECUTION_FILE"
          exit 1
        fi

    # Process and publish the review results
    - name: Process review results
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-app-token || inputs.github-token }}
        OUTPUT_DIR: ${{ inputs.output-dir }}
        REVIEW_SCHEMA_FILE: ${{ inputs.schema-file }}
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        cd ${{ github.action_path }}
        # Use the schema file that was created by run_review.py
        # If no schema file was provided as input, use the one in output directory
        SCHEMA_FILE="${{ inputs.schema-file }}"
        if [ -z "$SCHEMA_FILE" ] && [ -f "${{ inputs.output-dir }}/review-schema.json" ]; then
          SCHEMA_FILE="${{ inputs.output-dir }}/review-schema.json"
        fi
        uv run --python 3.13 -m cletus_code.process_review \
          --output-dir "${{ inputs.output-dir }}" \
          ${SCHEMA_FILE:+--schema-file "$SCHEMA_FILE"}
