name: 'Cletus Code Review'
description: 'AI-powered pull request review with plugin support and auto-merge capabilities'
branding:
  icon: 'eye'
  color: 'purple'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}

  changed-files:
    description: 'JSON array of changed file paths from changed-files action'
    required: true

  skills:
    description: 'Array of review skills to use. Formats: local:skill-name, owner/repo:ref:skill-path, url:https://..., builtin:name'
    required: false

  extra-skills:
    description: 'Additional skills to include alongside defaults (JSON array string)'
    required: false

  output-dir:
    description: 'Directory for output files'
    required: false
    default: 'output'

  claude-args:
    description: 'Additional arguments to pass to Claude Code action'
    required: false
    default: '--dangerously-skip-permissions'

  anthropic-api-key:
    description: 'Anthropic API key for Claude Code'
    required: true

  schema-file:
    description: 'Path to schema file for review validation'
    required: false

  settings:
    description: 'JSON settings for Claude Code (for MCP servers, etc)'
    required: false

runs:
  using: 'composite'
  steps:
    # Setup Python
    - name: Setup Python
      shell: bash
      run: |
        if command -v uv &> /dev/null; then
          echo "uv already installed"
        else
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
        fi
        export PATH="$HOME/.local/bin:$PATH"
        uv --version
        uv python install 3.13

    # Run the review orchestrator
    - name: Run review orchestrator
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        CHANGED_FILES: ${{ inputs.changed-files }}
        CLETUS_SKILLS: ${{ inputs.skills }}
        CLETUS_EXTRA_SKILLS: ${{ inputs.extra-skills }}
        OUTPUT_DIR: ${{ inputs.output-dir }}
        REVIEW_SCHEMA_FILE: ${{ inputs.schema-file }}
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        cd ${{ github.action_path }}
        uv run --python 3.13 -m cletus_code.run_review \
          --changed-files '${{ inputs.changed-files }}' \
          ${{ inputs.skills != '' && format('--skills-json {0}', inputs.skills) || '' }} \
          ${{ inputs.extra-skills != '' && format('--extra-skills {0}', inputs.extra-skills) || '' }} \
          --output-dir "${{ inputs.output-dir }}"

    # Run Claude Code with the generated prompt
    - name: Run Claude Code
      uses: anthropics/claude-code-action/base-action@7145c3e0510bcdbdd29f67cc4a8c1958f1acfa2f # v1.0.27
      with:
        prompt_file: ${{ github.action_path }}/${{ inputs.output-dir }}/claude-prompt.md
        anthropic_api_key: ${{ inputs.anthropic-api-key }}
        # Base action doesn't accept github_token input? Let's check.
        # It accepts env vars but inputs...
        # Cat output showed inputs: settings, anthropic_api_key...
        # Does it allow github_token?
        # Inputs: prompt, prompt_file, settings, anthropic_api_key, claude_code_oauth_token, use_bedrock...
        # It does NOT list github_token in inputs!
        # But it sets env: GITHUB_TOKEN?
        # No, base-action action.yml doesn't seem to set GITHUB_TOKEN or GH_TOKEN from inputs.
        # It runs bun run index.ts.
        # index.ts likely reads process.env.GITHUB_TOKEN.
        # So I should pass env: GITHUB_TOKEN: ${{ inputs.github-token }}
        # And NOT with: github_token
        claude_args: ${{ inputs.claude-args }}
        settings: ${{ inputs.settings }}
        show_full_output: 'true'
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        # Also try passing anthropic_api_key as env var just in case
        ANTHROPIC_API_KEY: ${{ inputs.anthropic-api-key }}

    # Copy review output from workspace to action directory
    - name: Copy review output
      shell: bash
      run: |
        # Claude Code writes to output/review.json in the workspace
        # We need to copy it to the action's output directory
        if [ -f "${{ github.workspace }}/output/review.json" ]; then
          mkdir -p "${{ github.action_path }}/${{ inputs.output-dir }}"
          cp "${{ github.workspace }}/output/review.json" "${{ github.action_path }}/${{ inputs.output-dir }}/review.json"
          echo "Copied review.json from workspace to action directory"
        else
          echo "Warning: review.json not found in workspace at ${{ github.workspace }}/output/review.json"
          ls -la "${{ github.workspace }}/output/" || echo "output directory doesn't exist"
        fi

    # Process and publish the review results
    - name: Process review results
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        OUTPUT_DIR: ${{ inputs.output-dir }}
        REVIEW_SCHEMA_FILE: ${{ inputs.schema-file }}
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        cd ${{ github.action_path }}
        uv run --python 3.13 -m cletus_code.process_review \
          --output-dir "${{ inputs.output-dir }}" \
          ${{ inputs.schema-file != '' && format('--schema-file {0}', inputs.schema-file) || '' }}
